# Generated by Django 5.0.4 on 2024-05-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="published_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
