# Generated by Django 5.0.4 on 2024-05-06 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0002_alter_newspaper_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="publishers",
            field=models.ManyToManyField(
                related_name="newspapers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
