# Generated by Django 5.0.4 on 2024-05-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0004_rename_context_newspaper_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="redactor",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
