# Generated by Django 5.0.4 on 2024-05-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0006_alter_redactor_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={},
        ),
        migrations.AlterField(
            model_name="redactor",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="redactor",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="redactor",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
